[BUILDBOT] Document and streamline our build scripts. With shared and per-builder settings, we can now have a buildslave with multiple builders. More configuration settings also allow these scripts to be finally deployed on all our Linux buildslaves.
svn path=/trunk/buildbot/; revision=2146

diff --git a/scripts/Linux/patching b/scripts/Linux/patching
--- a/scripts/Linux/patching
+++ b/scripts/Linux/patching
@@ -4,26 +4,37 @@
 #
 # Parameter $1 - Attachment ID
 
+clean_exit()
+{
+	# Disable rostests again to restore the defined state of our tree
+	mv modules/rostests modules/rostests_disabled 2>/dev/null
+	exit $1
+}
+
 if [ "$1" = "" ]; then
-    echo "Skipping patch phase"
-    exit 0
+	echo "Skipping patch phase"
+	exit 0
 fi
 
 echo "* Downloading patch."
 wget -q --output-document=default.patch "http://jira.reactos.org/secure/attachment/$1/" || exit $?
 
 if ! grep -q "Index:" default.patch; then
-    echo "Not a patch file!"
-    exit 1
+	echo "Not a patch file!"
+	exit 1
 fi
 
+# Let's be able to apply patches to modules/rostests
+mv modules/rostests_disabled modules/rostests 2>/dev/null
+
 echo "* Performing a dry-run."
-patch -u -i default.patch -p0 --verbose --dry-run > check.txt || exit $?
+patch -u -i default.patch -p0 --verbose --dry-run | tee check.txt || clean_exit $?
 
 if grep -q "FAILED --" check.txt; then
-    echo "Applying patch failed!"
-    exit 1
+	echo "Applying patch failed!"
+	clean_exit 1
 fi
 
 echo "* Applying patch."
 patch -u -i default.patch --verbose -p0
+clean_exit $?
